# Generated by Django 5.0.1 on 2024-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='id',
        ),
        migrations.AlterField(
            model_name='sites',
            name='site_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
