# Generated by Django 5.0.1 on 2024-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_sites_id_alter_sites_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='template_files/')),
            ],
        ),
    ]
