# Generated by Django 5.0.1 on 2024-03-10 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promo_code', models.CharField(max_length=50)),
                ('referral_link', models.URLField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sites')),
            ],
        ),
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='casino_logos/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sites')),
            ],
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
        migrations.AddField(
            model_name='bonus',
            name='casino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.casino'),
        ),
    ]
