# Generated by Django 5.0.1 on 2024-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_bonus_casino_content_delete_templates_bonus_casino'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='apk_file',
            field=models.FileField(default='default_apk.apk', upload_to='file/'),
        ),
        migrations.AddField(
            model_name='sites',
            name='hero_image',
            field=models.ImageField(default='hero.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='sites',
            name='logo',
            field=models.ImageField(default='logo.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='sites',
            name='name',
            field=models.CharField(default='doghouse.best', max_length=100),
        ),
        migrations.AlterField(
            model_name='casino',
            name='logo',
            field=models.ImageField(default='cas_logo.jpg', upload_to='img/'),
        ),
    ]
