# Generated by Django 4.2.11 on 2024-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_sites_apk_file_sites_hero_image_sites_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='slot_name',
            field=models.CharField(default='The Dog House', max_length=200),
        ),
        migrations.AlterField(
            model_name='sites',
            name='name',
            field=models.CharField(default='doghouse.best', max_length=200),
        ),
    ]
