# Generated by Django 4.2.11 on 2024-03-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_sites_slot_name_alter_sites_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='provider_name',
            field=models.CharField(default='Pragmatic Play', max_length=200),
        ),
    ]
