# Generated by Django 4.2.11 on 2024-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_content_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='demo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sites',
            name='promo_image',
            field=models.ImageField(default='promo.jpg', upload_to='img/'),
        ),
    ]
