# Generated by Django 4.2.11 on 2024-03-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_sites_demo_sites_promo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
