# Generated by Django 4.2.11 on 2024-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_content_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='yt_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
