# Generated by Django 4.2.11 on 2024-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_content_yt_link_alter_content_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='yt_link',
        ),
        migrations.AddField(
            model_name='sites',
            name='yt_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
