# Generated by Django 4.2.11 on 2024-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_sites_tlg_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='favicon',
            field=models.ImageField(default='favicon.ico', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
