# Generated by Django 4.2.11 on 2024-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_sites_favicon_alter_content_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_id', models.CharField(max_length=500, unique=True)),
                ('target_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='sites',
            name='apk_file',
            field=models.FileField(default='', upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='favicon',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='hero_image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sites',
            name='promo_image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='provider_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sites',
            name='slot_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sites',
            name='tlg_link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
