# Generated by Django 4.2.11 on 2024-03-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_redirect_alter_sites_apk_file_alter_sites_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirect',
            name='redirect_id',
        ),
        migrations.AlterField(
            model_name='redirect',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
