# Generated by Django 4.2.11 on 2024-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_remove_redirect_redirect_id_alter_redirect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
