# Generated by Django 4.2.11 on 2024-03-21 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_redirect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='redirect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.redirect'),
            preserve_default=False,
        ),
    ]
