# Generated by Django 4.2.11 on 2024-03-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_sites_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='redirect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.redirect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casino',
            name='redirect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.redirect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sites',
            name='counters',
            field=models.TextField(default=''),
        ),
    ]
