# Generated by Django 4.2.11 on 2024-03-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_redirect_visits_alter_casino_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='allowed_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sites',
            name='apk_file',
            field=models.FileField(blank=True, default='', upload_to='file/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='counters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sites',
            name='demo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sites',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='hero_image',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='promo_image',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='provider_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sites',
            name='redirect',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='config.redirect'),
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_clicked', models.DateTimeField(auto_now_add=True)),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.redirect')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sites')),
            ],
        ),
    ]
