# Generated by Django 4.2.11 on 2024-03-31 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_alter_sites_allowed_domain_alter_sites_apk_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='date_clicked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
