# Generated by Django 4.2.11 on 2024-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_sites_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
