# Generated by Django 4.2.11 on 2024-04-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_aff'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='aff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.aff'),
        ),
    ]
