# Generated by Django 4.2.11 on 2024-04-06 07:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_redirect_aff'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='aff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.aff'),
        ),
        migrations.CreateModel(
            name='AffReg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_id', models.PositiveIntegerField()),
                ('promo_id', models.PositiveIntegerField()),
                ('visit_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('aff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.aff')),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.click')),
            ],
        ),
    ]
