# Generated by Django 4.2.11 on 2024-04-06 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0026_click_aff_affreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffDep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_id', models.PositiveIntegerField()),
                ('promo_id', models.PositiveIntegerField()),
                ('visit_id', models.PositiveIntegerField()),
                ('player_id', models.PositiveIntegerField()),
                ('amount', models.FloatField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('deposit_id', models.PositiveIntegerField()),
                ('reg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('aff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='config.aff')),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.click')),
            ],
        ),
    ]
