# Generated by Django 4.2.11 on 2024-04-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_affdep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affdep',
            old_name='reg_date',
            new_name='dep_date',
        ),
        migrations.AddField(
            model_name='affdep',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
