# Generated by Django 4.2.11 on 2024-04-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_alter_affreg_visit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affdep',
            name='visit_id',
            field=models.CharField(max_length=100),
        ),
    ]
