# Generated by Django 4.2.11 on 2024-04-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0030_alter_affdep_visit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affdep',
            name='click',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='config.click'),
        ),
        migrations.AlterField(
            model_name='affreg',
            name='click',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='config.click'),
        ),
    ]
