# Generated by Django 4.2.11 on 2024-04-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_alter_affdep_click_alter_affreg_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='redirect',
        ),
    ]
