# Generated by Django 4.2.11 on 2024-04-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_remove_sites_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.sites'),
        ),
    ]
