# Generated by Django 4.2.11 on 2024-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_redirect_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='sorting_order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
