# Generated by Django 4.2.11 on 2024-04-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_bonus_sorting_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('sorting_order', models.PositiveIntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='img/')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sites')),
            ],
        ),
    ]
