# Generated by Django 4.2.11 on 2024-04-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
