# Generated by Django 4.2.11 on 2024-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_redirect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='type',
            field=models.CharField(blank=True, default='CPA', max_length=100, null=True),
        ),
    ]
