# Generated by Django 4.2.11 on 2024-04-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_alter_redirect_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, default='', upload_to='img/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sites')),
            ],
        ),
    ]
