# Generated by Django 4.2.11 on 2024-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='in_gallery',
            field=models.BooleanField(default=True),
        ),
    ]
