# Generated by Django 4.2.11 on 2024-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0041_image_in_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
    ]
