# Generated by Django 4.2.11 on 2024-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0042_sites_custom_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='background_color_primary',
            field=models.CharField(blank=True, default='#1a0e1e', max_length=10),
        ),
        migrations.AddField(
            model_name='sites',
            name='background_color_secondary',
            field=models.CharField(blank=True, default='#33263a', max_length=10),
        ),
        migrations.AddField(
            model_name='sites',
            name='primary_color',
            field=models.CharField(blank=True, default='darksalmon', max_length=10),
        ),
        migrations.AddField(
            model_name='sites',
            name='secondary_color',
            field=models.CharField(blank=True, default='#48c78e', max_length=10),
        ),
    ]
