# Generated by Django 4.2.11 on 2024-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0043_sites_background_color_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
