# Generated by Django 4.2.11 on 2024-05-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0046_sites_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='hero_image_is_rounded',
            field=models.BooleanField(default=False),
        ),
    ]
