# Generated by Django 4.2.11 on 2024-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0047_sites_hero_image_is_rounded'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='interface_image',
            field=models.ImageField(blank=True, default='', upload_to='interface-img/'),
        ),
    ]
