# Generated by Django 4.2.11 on 2024-06-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0048_sites_interface_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamblingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField()),
                ('info', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, default='', upload_to='gambling-resources-img/')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
    ]
