# Generated by Django 4.2.11 on 2024-07-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0049_gamblingresource_content_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='provider_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
