# Generated by Django 4.2.11 on 2024-09-24 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0052_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='logo_svg',
            field=models.FileField(default='logo.svg', upload_to='img/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
