# Generated by Django 4.2.11 on 2024-09-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0054_sites_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='casino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.casino'),
        ),
    ]
