# Generated by Django 4.2.11 on 2024-09-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0055_sites_casino'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
