# Generated by Django 4.2.11 on 2024-09-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0056_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
