# Generated by Django 4.2.11 on 2024-09-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0057_casino_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
