# Generated by Django 4.2.11 on 2024-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0058_alter_image_description_alter_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='keywords',
            field=models.CharField(max_length=1000),
        ),
    ]
