# Generated by Django 4.2.11 on 2024-09-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0059_alter_content_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='custom_css',
            field=models.TextField(blank=True),
        ),
    ]
