# Generated by Django 4.2.11 on 2024-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0060_casino_custom_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='demo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='is_version_page',
            field=models.BooleanField(default=True),
        ),
    ]
