# Generated by Django 4.2.11 on 2024-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0062_remove_content_is_version_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_version_page',
            field=models.BooleanField(default=False),
        ),
    ]
