# Generated by Django 4.2.11 on 2024-09-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_content_is_version_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='casino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.casino'),
        ),
    ]
