# Generated by Django 4.2.11 on 2024-10-03 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0065_sites_slot_rtp_alter_sites_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='favicon',
            field=models.FileField(default='favicon.ico', upload_to='favicons/', validators=[django.core.validators.FileExtensionValidator(['ico'])]),
        ),
    ]
