# Generated by Django 4.2.11 on 2024-10-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0067_alter_casino_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='interface_image',
            field=models.ImageField(blank=True, default='', upload_to='interface-img/'),
        ),
    ]
