# Generated by Django 5.0.9 on 2024-11-18 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0068_content_interface_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='css_file',
            field=models.FileField(blank=True, default='silicon.html', upload_to='css/'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='favicon',
            field=models.FileField(default='favicon.ico', upload_to='favicons/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'svg', 'webp'])]),
        ),
    ]
