# Generated by Django 5.0.9 on 2024-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0069_sites_css_file_alter_casino_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='css_file',
            field=models.FileField(blank=True, default='css/dark.css', upload_to='css/'),
        ),
    ]
