# Generated by Django 4.2.13 on 2024-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0071_casino_alternative_name_alter_casino_logo_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='interface_image_webp',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='sites',
            name='logo_svg',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
    ]
