# Generated by Django 4.2.13 on 2024-11-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0072_sites_interface_image_webp_sites_logo_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='favicon_file',
            field=models.FileField(blank=True, upload_to='favicon/'),
        ),
    ]
