services:

  multidor:
    container_name: multidor
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 2 -b 0.0.0.0:8000 multidor.wsgi:application
    ports:
      - 8000
    volumes:
      - ./multidor/db.sqlite3:/app/multidor/db.sqlite3
      - ./multidor/media:/app/multidor/media
    restart: always
    networks:
      - shared-network

  pragmatic:
    container_name: pragmatic
    build:
      context: ./pragmat
      dockerfile: Dockerfile
    command: gunicorn -w 2 -b 0.0.0.0:8888 pragmatic.wsgi:application
    ports:
      - 8888
    volumes:
      - ./pragmat/staticfiles:/app/pragmat/staticfiles
    restart: always
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./multidor/templates:/app/multidor/templates
      - ./multidor/static:/app/multidor/static
      - ./multidor/media:/app/multidor/media
    depends_on:
      - multidor
    restart: always
    networks:
      - shared-network

networks:
  shared-network:
