version: '3'

services:

  multidor:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:8000 multidor.wsgi:application
    ports:
      - 8000:8000
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./multidor/templates:/app/multidor/templates
      - ./multidor/media:/app/multidor/media
    depends_on:
      - multidor
    restart: always

  webhook:
    image: almir/webhook
    container_name: webhook
    command: -verbose -hooks=/etc/webhook/hooks.json -hotreload
    environment:
      - TZ=America/New_York
    volumes:
      - ./deploy/hooks.json:/etc/webhook/hooks.json
      - ./:/opt/git
    ports:
      - 9000:9000
    restart: always