# Generated by Django 4.2.13 on 2024-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='rating',
            field=models.IntegerField(default=96),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='rtp',
            field=models.IntegerField(default=96),
            preserve_default=False,
        ),
    ]
