# Generated by Django 4.2.13 on 2024-06-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_slot_rating_slot_rtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='users_choice',
            field=models.BooleanField(default=False),
        ),
    ]
