# Generated by Django 4.2.13 on 2024-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='rtp',
            field=models.FloatField(),
        ),
    ]
