# Generated by Django 4.2.13 on 2024-06-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_alter_slot_rating_alter_slot_rtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='snippet',
            field=models.TextField(blank=True),
        ),
    ]
