# Generated by Django 4.2.13 on 2024-06-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_slot_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='sorting_order',
            field=models.FloatField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
