# Generated by Django 4.2.13 on 2024-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0007_slot_sorting_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
