# Generated by Django 4.2.13 on 2024-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0008_slot_is_new_slot_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
