# Generated by Django 4.2.13 on 2024-06-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0009_alter_slot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='folk_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
