# Generated by Django 4.2.11 on 2024-10-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0007_site_base_template_site_page_detail_template_and_more'),
        ('slots', '0011_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pragmatic.provider'),
        ),
    ]
