# Generated by Django 4.2.11 on 2024-10-06 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0007_site_base_template_site_page_detail_template_and_more'),
        ('slots', '0013_alter_slot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pragmatic.site')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.slot')),
            ],
        ),
    ]
