# Generated by Django 4.2.11 on 2024-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0014_slotdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
