# Generated by Django 4.2.11 on 2024-10-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0015_slottype'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.slottype'),
        ),
    ]
