# Generated by Django 4.2.11 on 2024-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0016_slot_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='version',
            field=models.CharField(default='1.0.0', max_length=100),
        ),
    ]
