# Generated by Django 4.2.11 on 2024-10-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0017_slot_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
