# Generated by Django 4.2.11 on 2024-10-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0021_paylines'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='features',
            field=models.ManyToManyField(blank=True, to='slots.feature'),
        ),
        migrations.AddField(
            model_name='slot',
            name='paylines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.paylines'),
        ),
        migrations.AddField(
            model_name='slot',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.theme'),
        ),
    ]
