# Generated by Django 4.2.11 on 2024-10-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0022_slot_features_slot_paylines_slot_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='paylines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.paylines'),
        ),
    ]
