# Generated by Django 4.2.11 on 2024-10-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0023_alter_slot_paylines'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottype',
            name='plural',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
