# Generated by Django 4.2.11 on 2024-10-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0009_language'),
        ('slots', '0024_slottype_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdescription',
            name='language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pragmatic.language'),
        ),
    ]
