# Generated by Django 4.2.11 on 2024-10-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0025_slotdescription_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='russian_title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='paylines',
            old_name='russian_title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='russian_title',
            new_name='title_ru',
        ),
    ]
