# Generated by Django 4.2.11 on 2024-10-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0026_rename_russian_title_feature_title_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='paylines',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='title',
            new_name='title_en',
        ),
    ]
