# Generated by Django 4.2.11 on 2024-10-20 13:32

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0027_rename_title_feature_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='title_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_es',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_pt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paylines',
            name='title_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paylines',
            name='title_es',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paylines',
            name='title_pt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_de',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_es',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_pt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title_en', unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paylines',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title_en', unique=True),
        ),
        migrations.AlterField(
            model_name='paylines',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paylines',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title_en', unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
