# Generated by Django 4.2.11 on 2024-10-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0028_feature_title_de_feature_title_es_feature_title_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paylines',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
