# Generated by Django 4.2.11 on 2024-10-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0029_feature_title_paylines_title_theme_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='title',
        ),
        migrations.RemoveField(
            model_name='paylines',
            name='title',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='title',
        ),
    ]
