# Generated by Django 4.2.11 on 2024-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0032_providersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providersetting',
            old_name='value',
            new_name='value_de',
        ),
        migrations.AddField(
            model_name='providersetting',
            name='value_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providersetting',
            name='value_es',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providersetting',
            name='value_pt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providersetting',
            name='value_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
