# Generated by Django 4.2.11 on 2024-10-26 10:10

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0033_rename_value_providersetting_value_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='description_de',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_pt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_de',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='title_es',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='title_pt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title_en', unique=True),
        ),
    ]
