# Generated by Django 4.2.11 on 2024-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0034_rename_description_page_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='similar_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
