# Generated by Django 4.2.11 on 2024-11-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0035_slot_similar_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.theme'),
        ),
    ]
