# Generated by Django 4.2.11 on 2024-10-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_name', models.CharField(max_length=255)),
                ('redirect_url', models.CharField(max_length=255)),
            ],
        ),
    ]
