# Generated by Django 4.2.11 on 2024-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='offers',
            field=models.ManyToManyField(blank=True, to='pragmatic.offer'),
        ),
    ]
