# Generated by Django 4.2.11 on 2024-10-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0007_site_base_template_site_page_detail_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='base_template',
            field=models.CharField(default='base.html', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='home_template',
            field=models.CharField(default='home.html', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='page_detail_template',
            field=models.CharField(default='page_detail.html', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='slot_detail_template',
            field=models.CharField(default='slot_detail.html', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='slot_list_template',
            field=models.CharField(default='slot_list.html', max_length=50),
        ),
    ]
