# Generated by Django 4.2.11 on 2024-10-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0011_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pragmatic.provider'),
            preserve_default=False,
        ),
    ]
