# Generated by Django 4.2.11 on 2024-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0012_faq_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='counters',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
