# Generated by Django 4.2.11 on 2024-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0013_site_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='redirect_subdomain',
            field=models.CharField(default='www', max_length=30),
        ),
    ]
