# Generated by Django 4.2.11 on 2024-11-01 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0014_site_redirect_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='logo_dark_mode',
            field=models.FileField(null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='offer',
            name='logo_light_mode',
            field=models.FileField(null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['ico', 'png', 'svg', 'webp'])]),
        ),
    ]
