# Generated by Django 4.2.11 on 2024-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0015_offer_logo_dark_mode_offer_logo_light_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='notfound_template',
            field=models.CharField(default='404.html', max_length=50),
        ),
    ]
