# Generated by Django 4.2.11 on 2024-11-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0016_site_notfound_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='counters',
            field=models.TextField(blank=True),
        ),
    ]
