# Generated by Django 4.2.11 on 2024-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0017_alter_site_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
