# Generated by Django 4.2.13 on 2024-11-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pragmatic', '0018_offer_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='banned_domains',
            field=models.TextField(blank=True),
        ),
    ]
